# Generated by Django 4.2.6 on 2023-11-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_quantity', models.IntegerField()),
                ('product_details', models.TextField(blank=True)),
            ],
        ),
    ]
