# Generated by Django 4.2.6 on 2023-11-02 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='shop.productdetails'),
        ),
    ]
